### ISSUE TITLE
Text on Home page (formerly "Hi.")

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/GR8975-edition#29]
What text should be on the home page where "Hi" is now

**Comment by xl2668** [comment]
The Manuscript BnF Ms Fr 640, now preserved at Bibliothèque nationale de France, is a artisan’s how-to book or book of secrets written by an experienced practitioner in sixteenth-century, who was like worked in the vicinity of Toulouse, France. In its 171 folios, the manuscript contains the written record of the author-practitioner’s collection of recipes and his workshop investigations. It consists of a remarkable scope of techniques includes casting, molding, metalwork, pigment and varnish making, painting, practical therapeutics, vernacular natural history, perspective and optics, mechanics, and even jokes and sleight-of-hand tricks, etc. It offers a remarkable window into the early modern artisan’s workshop, revealing not only the materials and methods of artisans and practitioners, but also insights into how and why nature was studied, investigated, represented in early modern period.

**Comment by tcatapano** [comment]
Closing
