### ISSUE TITLE
Markup for entries that span two folios

### ISSUE THREAD

**Issue by jwayno** [cu-mkp/GR8975-edition#34]
How are we marking up entries that span one or more folios? I looked through the xml files for an example and found this:

start="108r"
end="108v"
url="http://gallica.bnf.fr/ark:/12148/btv1b10500001g/f221.image"
url2="http://gallica.bnf.fr/ark:/12148/btv1b10500001g/f222.image"/>

But our DTD is telling me that isn't valid, so I think we either need to change the DTD or come up with something else. Have a missed something here?

**Comment by Nikhil-Ramachandran** [comment]
at the start of each folio page have an empty folio element
"<folio number="108r" url=    />"
"<folio number="108v" url=   />" 
 this should work.

**Comment by thuchacz** [comment]
@Nikhil-Ramachandran  if you want to show code between \<>, you need to put a "\" in front of it, otherwise, github treats those brackets as an indication of code itself!

**Comment by Nikhil-Ramachandran** [comment]
thanks @thuchacz 
@jwayno 
to handle multiple folios, place an empty folio element when the entry breaks into another folio.
The below example worked for me

```xml
<entry>
<folio number="108r" url=""/>
<block>
</block>
<folio number="108v" url=""/>
<block>
</block>
</entry>
```

**Comment by tcatapano** [comment]
Previous entry has correct markup. Closing
