### ISSUE TITLE
missing entry titles in TOC

### ISSUE THREAD

**Issue by Nikhil-Ramachandran** [cu-mkp/GR8975-edition#35]
In the TOC, not sure why the headings/titles of p141r_1 and p142_3 are not showing up. Tried looking at the markdown files, but could not troubleshoot.

**Comment by thuchacz** [comment]
I have the same problem with p009v_1.

**Comment by tcatapano** [comment]
Cannot figure this out either. For some reason these pages are not being processed the same on conversion to html by jekyll. Looking into it.

**Comment by tcatapano** [comment]
Should be fixed now. Problem was with empty values in categrories and materials YAML lists. Source was entry-to-md.xsl. Closing

**Comment by tcatapano** [comment]
Reopening. See 

- https://cu-mkp.github.io/GR8975-edition/texts/p015v_4/
- https://cu-mkp.github.io/GR8975-edition/texts/p134r_2/
- and entry following 137r_3

**Comment by ps2270** [comment]
6r and 10r titles missing in the ToC.

**Comment by tcatapano** [comment]
Fixed. Closing
