### ISSUE TITLE
Introduction to Minimal Edition

### ISSUE THREAD

**Issue by sohinichatt** [cu-mkp/GR8975-edition#39]
##Introduction to the Minimal Edition

The digital minimal edition is a course project of the graduate-level digital humanities seminar, **“HIST GR8975: What is a Book in the 21st Century?”** offered the by Department of History at Columbia University.  Students worked collaboratively and creatively in the process of producing this edition. The English translation of BnF Ms. Fr. 640 is the basic data set of the minimal edition. This edition has basic and limited feature, yet serves as important prototype for the design of the Project’s final digital critical edition.The project is an integral part of the Making and Knowing Project, and is in close collaboration with other researches on the Making and Knowing Project. 

The organization of the content in this edition corresponds to that in Ms. Fr. 640. The organizing element of the manuscript is called ‘entry’. These entries are individual or related instructions or observations on the experimentation with different crafts and natural materials. Students have marked up the structure of the entry, including identifier, title, main body of the text, marginalia and illustration. They have also used markup to identify specific elements in the entry, such as materials, tools, activities, names, etc. The presentation of the texts is in accordance with that in the original manuscript. The edition is electronically searchable and intuitive user-directed. 

This digital edition is hosted on ‘Jekyll’, a minimal computing platform. It is designed to provide easy and enhanced reading experiences, and to encourage interaction with the content of the manuscript itself. It is open-access to encourage wider scope of innovative reading and research.

**Comment by tcatapano** [comment]
taking over from issue #31

**Comment by tcatapano** [comment]
add text to file intro.md
