### ISSUE TITLE
Order of ToC

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/GR8975-edition#44]
The order of my entries in the ToC does not follow the order of the folio, e.g., 1r_a1 is not followed by 1r_a2, rather they seem to be in random order.  Why would this be?

**Comment by tcatapano** [comment]
@ps2270: I think this has to do with the naming of the files. In the XML the identifier for entry p001r_a4  is lacking the "p":

https://github.com/cu-mkp/GR8975/blob/master/xml/p001r_a4.xml

the XSLT uses the identifier to generate the filename for the md file in _texts, so the filename for that entry is "001r_p4.md" and therefore sorts before everything else.

**Comment by ps2270** [comment]
got it, and changed the entries on fol. 1r to all be consistent.  but why do you say that the filename is ...p4.md?  Not .xml?  Is that my mistake?

**Comment by tcatapano** [comment]
@ps2270: The _texts/*.md files are generated from the xml/*.xml files via the xslt/entry-to-md.xsl XSLT transformation. We edit only the xml files -- they are the "files of record". The *.md files are the input to Jekyll/Ed, but they are "derivatives" of the richer XML source.

**Comment by tcatapano** [comment]
Still getting some problems with the ordering and now repetition of entries in TOC.

The order is affected by the form of the id/basename. E.g., "p001r_4" will sort before "p001r_a1". We should probably settle on the form of the id *or* introduce and explicit sequence # field in the YAML headers

The repetition of entries in the TOC is a mystery. Perhaps this is a by product of Jekyll not flushing a cache when it regenerates.

**Comment by ps2270** [comment]
Can we fix this problem of ordering and now repetition of entries before the launch?

**Comment by tcatapano** [comment]
fixed. closing
