### ISSUE TITLE
"About" content for edition is updated and needs review

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/GR8975-edition#53]
I have now updated About M&K, About the Ms, and About the Edition.  In the latter two, the content about the Ed platform BUILT BY ALEX GIL AND TERRY CATAPANO (right?) needs to be fleshed out and corrected.

**Comment by zhaowenrui** [comment]
for "About the Edition", a minor issue - the whole phrase of "unit of measure" should be italicized I think (it's in the sentence "They agreed collectively on a markup schema for the text that included specific elements in each entry: purpose, activity, material, tool, name, profession, unit of measure, plant, animal, currency, foreign language, material format, place, time, and color")

**Comment by tcatapano** [comment]
Closing
