### ISSUE TITLE
"About" content for course

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/GR8975-edition#54]
Jeffrey, the "About content for the course" now contains the google doc links to the syllabus.  When you finish updating the syllabus on Github, could you please substitute the link.  I don't know if we can transfer the schedule and competencies to Github, or whether it must live on the Gogle drive and be accessible there.

**Comment by ps2270** [comment]
Jeffrey,
we decided just to link to gd.
thanks for your work on it.

**Comment by jwayno** [comment]
Okay, Pamela, sounds good. See you tomorrow!

Jeffrey
