### ISSUE TITLE
Credits page needs update 

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/GR8975-edition#62]
The History Dept changed their website, and now the link under Pamela's bio sends to a "no results found" page. 
The wrong one is: http://history.columbia.edu/faculty/Smith.html
The correct one is: http://history.columbia.edu/faculty/smith-pamela-h/

This is true for any History Dept links (eg Wenrui's link), but it seems important that at minimum this is fixed for the instructor.

Terry - Can you make this edit? Thank you!!! :)
Pamela - Do you want all Hist Dept links fixed?

**Comment by tcatapano** [comment]
Fixed. Closing
